# fly.toml app configuration file generated for billowing-wave-7639 on 2023-05-27T14:38:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-wave-7639"
primary_region = "scl"

[http_service]
  internal_port = 3110
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
